steps:
  # Build backend
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/golden-cosmos-450417-i8/testifi-backend:$SHORT_SHA",
        "--target=backend",
        ".",
      ]

  # Build summarize-worker
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/golden-cosmos-450417-i8/summarize-worker:$SHORT_SHA",
        "--target=summarize-worker",
        ".",
      ]

  # Push both images
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/golden-cosmos-450417-i8/testifi-backend:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/golden-cosmos-450417-i8/summarize-worker:$SHORT_SHA"]

  # Deploy worker separately
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "set"
      - "image"
      - "deployment/summarize-worker"
      - "summarize-worker=gcr.io/golden-cosmos-450417-i8/summarize-worker:$SHORT_SHA"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=testifi"

substitutions:
  _DB_HOST: "127.0.0.1" # Cloud SQL Proxy runs on localhost

images:
  - "gcr.io/golden-cosmos-450417-i8/testifi-backend:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: "748916208557-compute@developer.gserviceaccount.com"
