import { cn } from "@/lib/utils";

interface DisclaimerNoticeProps {
  className?: string;
}

export const DisclaimerNotice = ({ className }: DisclaimerNoticeProps) => (
  <p
    className={cn(
      "text-xs leading-relaxed text-slate-500 dark:text-slate-400",
      className
    )}
  >
    <span className="font-semibold text-slate-600 dark:text-slate-300">
      Disclaimer:
    </span>{" "}
    The information on this website, blog, and articles applies only to U.S.
    practices. It is provided for informational purposes only and does not
    constitute legal, business, or accounting advice. Any summaries generated by
    Testifi AI require human oversight at all times.
  </p>
);
