-- AlterTable
ALTER TABLE `SummaryJob` ADD COLUMN `finishedAt` DATETIME(3) NULL,
    ADD COLUMN `startedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ALTER COLUMN `updatedAt` DROP DEFAULT;
