steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/testifi-backend:${_TAG}', '--target', 'backend', '.']
    dir: 'backend'
images:
  - 'gcr.io/${PROJECT_ID}/testifi-backend:${_TAG}'
substitutions:
  _TAG: staging
