apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: testifi-frontend
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "2"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 60
      containers:
        - image: gcr.io/golden-cosmos-450417-i8/testifi-frontend:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
