steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/summarize-worker:${_TAG}', '--target', 'summarize-worker', '.']
    dir: 'backend'
images:
  - 'gcr.io/${PROJECT_ID}/summarize-worker:${_TAG}'
substitutions:
  _TAG: latest
